itsmohit097/medi-hub

frontend/src/pages/AboutUs.jsx

Hey Mohit I have followed the steps and created a new PR kindly check this feature under #18 
Kindly assign GSSOC and level to me 
THANKU

[FEAT]: Adding about us page

---

frontend/src/App.jsx
frontend/src/components/Footer.jsx
frontend/src/pages/PrivacyPolicy.jsx
frontend/src/pages/TermsAndConditions.jsx

Fixed issue #8 
Changed footer width to full screen and also added some styling.
Added routes to quick links.
Made social media icons clickable.

[Enhancement]: Improving footer section style and adding functionality

---

dashboard/package-lock.json
dashboard/package.json
dashboard/postcss.config.js
dashboard/src/components/SideNavbar.jsx
dashboard/src/index.css
dashboard/src/pages/Home.jsx
dashboard/tailwind.config.js

```sh
(screenshot)
After changes:
(screenshot)
```

tailwind config done

---

frontend/src/components/Navbar.jsx

Fixed NavBar scrolling  issue
- Fixes #17 
```sh
(screenshot)
After changes:
(screenshot)
```

[Bug]: Sticky navbar on scrolling 

---

frontend/index.html
package-lock.json

```sh
(screenshot)
After changes:
(screenshot)
```

"Added Favicon and updated website title .

---

backend/src/controllers/contactus.controller.js
backend/src/models/contactus.model.js

```sh
(screenshot)
After changes:
(screenshot)
```

update contactus model and controller

---

frontend/src/components/Footer.jsx

```sh
(screenshot)
After changes:
(screenshot)
```

connect contact us with backend api

---

backend/app.js
backend/src/controllers/getInTouch.controller.js
backend/src/routes/getInTouch.routes.js

- Fixes #103 
```sh
(screenshot)
After changes:
(screenshot)
```

[Feat]: Setup sending mail api on contact us

---

frontend/src/components/Navbar.jsx

Changing the ui of current Navbar.
- Fixes #83

[Fix]: Creating a navbar fixed at top 

---

frontend/src/components/Hero.jsx

Created new hero section UI
- Fixes #84 

[ENHANCEMENT STYLING]: Creating a navbar fixed at top 

---

backend/.env.example
contributing.md

This pull request introduces a `.env.example` file to the project's backend directory. The file serves as a template for the necessary environment variables, helping developers set up their local environments quickly and consistently.
- Fixes #131 

Added .env.example

---

frontend/src/components/Footer.jsx

Updated Twitter logo to X logo.
- Fixes #68 
```sh
(scrrenshot)
After changes:
(screenshot)
```
@itsmohit097 kindly review the PR, thank you for your time.

[Bug]: Changed twitter logo to X

---

backend/src/controllers/user.controller.js

Certainly! Below is a template for your pull request description based on the issue you resolved:
---
This pull request introduces changes to add a controller function `getUserAppointmentInfo` that fetches information about a user and their doctor's appointment using the aggregation pipeline in MongoDB. The function retrieves detailed information about the user (patient) and the doctor associated with a given appointment.
- Fixes #27 using Aggregation Pipeline
```sh
(No controller to fetch user and doctor appointment details)
After changes:
Expected Behavior
{
"status": 200,
"data": {
"_id": "60f7c2c4c6e1c89e5f5e0d4f",
"appointmentDate": "2023-05-20T00:00:00.000Z",
"status": "Accepted",
"city": "New York",
"pincode": "10001",
"department": "Cardiology",
"patientDetails": { …
```

[ Feature]: Adding appointment info page to the backend (user's dashboard)

---

.github/workflows/greetings.yaml

Currently This repo does not have greeting bot. As it is a open source so many people create the issues. There is No one to greet the issue creator. GitHub greeting Bot will automatically greet them when they create a issue. I added github workflow to greet the issue creator and pr creator.
[Issue Link ](https://github.com/itsmohit097/medi-hub/issues/93) resolve #93 
- Fixes #93 

[FEAT]: Adding GitHub Automatic Greeting Bot

---

frontend/src/index.css

I have added a custom scroll-bar which matches with the website's UI. @itsmohit097 please review it and merge it to the main.
- Fixes #146 
After changes:

Fix #146: Added a custom scrollbar

---

frontend/src/components/Navbar.jsx

This pull request introduces a dropdown menu that appears when the login button is hovered over. The dropdown menu includes the following items:
- My Profile
- Appointments
- Wishlist
- Order
- Logout
- Fixes #33
```sh
After changes:
```

feat: add dropdown menu items (profile, appointments, wishlist, orde, logout on login button hover

---

frontend/src/components/Doctors.jsx

In this pull request I have improved the UI of the all doctors cards , and provided enough margin for the cards , which was not present before .
I have also made sure to use the default theme of the rest of the website by using custom colours which was already defined in the tailwind config file.
- Fixes #174 
(screenshot)
After changes:
(screenshot)

[ENHANCEMENT STYLING] Improve UI of the all doctors card 

---

frontend/src/pages/AllDoctors.jsx

Removed duplicate navbars in All Doctors Page
- Fixes #178 

Duplicate navbars removed

---

frontend/src/components/Hero.jsx
frontend/src/components/Navbar.jsx
frontend/src/index.css
frontend/tailwind.config.js

```sh
(screenshot)
After changes:
(screenshot)
```

new navbar (all issues fixed)

---

backend/package-lock.json
backend/package.json
backend/src/controllers/login_logout.controller.js
frontend/package-lock.json
frontend/package.json
frontend/src/pages/Login.jsx

Implemented reCAPTCHA v3 on the website (Login Button) that will help in enhancing security, preventing spam and unauthorized access, protecting user data.
This will also help in preventing automated bots from accessing or submitting forms on the website.
- Fixes #168 

feat: implemented-recaptcha

---

backend/app.js
backend/index.js
frontend/package-lock.json
frontend/src/pages/Login.jsx
frontend/src/pages/Signup.jsx

Login and signup functionality
Issue #105 
```sh
```

[Enhancement functionality]: API integration on login and signup

---

frontend/package-lock.json
frontend/src/components/Testamonial.jsx
frontend/src/import-export/ImportExport.js
frontend/src/pages/Home.jsx

Adding a new "Testimonial section" on the homepage
- Fixes #187
After changes:

ENHANCEMENT STYLING : Added a new Testimonial section on the hompage
